# This contain tasks to configure VLAG Tier1 Spine switches and further show it
---
- name: Replace VLAG Tier1 Spine CLI command template with values
  template: src=vlag_1tier_spine_common.j2 dest=./commands/cnos_vlag_1tier_spine_{{ inventory_hostname }}_common_commands.txt
  with_items: "{{ cnos_vlag_1tier_spine_data }}"

- name: Applying CLI commands on VLAG Tier1 Spine Switches
  cnos_template:
      host: {{ inventory_hostname }}
      username: "{{ hostvars[inventory_hostname]['ansible_ssh_user']}}"
      password: "{{ hostvars[inventory_hostname]['ansible_ssh_pass']}}"
      deviceType: "{{ hostvars[inventory_hostname]['deviceType']}}"
      commandfile: ./commands/cnos_vlag_1tier_spine_{{ inventory_hostname }}_common_commands.txt
      outputfile: ./results/cnos_vlag_1tier_spine_{{ inventory_hostname }}_common_output.txt
  with_items: "{{ cnos_vlag_1tier_spine_data }}"

- name: Replace VLAG Tier1 Spine CLI show template with values
  template: src=vlag_1tier_spine_show.j2 dest=./commands/cnos_vlag_1tier_spine_{{ inventory_hostname }}_show_commands.txt
  with_items: "{{ cnos_vlag_1tier_spine_data }}"

- name: Applying CLI show commands on VLAG Tier1 Spine Switches
  cnos_template:
      host: {{ inventory_hostname }}
      username: "{{ hostvars[inventory_hostname]['ansible_ssh_user']}}"
      password: "{{ hostvars[inventory_hostname]['ansible_ssh_pass']}}"
      deviceType: "{{ hostvars[inventory_hostname]['deviceType']}}"
      commandfile: ./commands/cnos_vlag_1tier_spine_{{ inventory_hostname }}_show_commands.txt
      outputfile: ./results/cnos_vlag_1tier_spine_{{ inventory_hostname }}_show_output.txt
  with_items: "{{ cnos_vlag_1tier_spine_data }}"
# Completed file
